import Link from 'next/link'
import { Calendar } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service – Hebelki',
  description: 'Terms of Service for Hebelki booking platform',
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b">
        <div className="mx-auto flex h-16 max-w-4xl items-center px-4">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-white">
              <Calendar className="h-5 w-5" />
            </div>
            <span className="text-xl font-bold">Hebelki</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-4 py-12">
        <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: February 2026</p>

        <div className="prose prose-gray max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">1. Scope</h2>
            <p className="text-gray-600">
              These Terms of Service govern your use of the Hebelki booking platform (&quot;Service&quot;),
              operated by Goldman Projects &amp; Ventures. By using the Service, you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">2. Service Description</h2>
            <p className="text-gray-600">
              Hebelki provides an online booking platform that allows businesses to manage appointments
              and customers to book services. The platform includes AI-powered chatbot functionality,
              booking management, and customer communication tools.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">3. Account Registration</h2>
            <p className="text-gray-600">
              To use business features, you must create an account. You are responsible for maintaining
              the security of your account credentials. You must provide accurate and complete information
              during registration.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">4. Acceptable Use</h2>
            <p className="text-gray-600 mb-2">You agree not to:</p>
            <ul className="list-disc pl-6 text-gray-600 space-y-1">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to the Service</li>
              <li>Interfere with or disrupt the Service</li>
              <li>Upload malicious content or code</li>
              <li>Violate the rights of others, including privacy rights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">5. Pricing and Payments</h2>
            <p className="text-gray-600">
              Hebelki offers free and paid plans. Paid plans are billed monthly or annually as selected.
              Prices are displayed in your local currency. All payments are processed securely through Stripe.
              You may cancel your subscription at any time, effective at the end of the current billing period.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">6. AI Chatbot</h2>
            <p className="text-gray-600">
              The AI chatbot is provided as an assistance tool. Responses generated by the AI may not always
              be accurate. Businesses are responsible for reviewing and maintaining their chatbot knowledge base.
              The chatbot clearly identifies itself as AI in compliance with the EU AI Act.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">7. Data Protection</h2>
            <p className="text-gray-600">
              We process personal data in accordance with our{' '}
              <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link>{' '}
              and applicable data protection laws, including the GDPR.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">8. Limitation of Liability</h2>
            <p className="text-gray-600">
              The Service is provided &quot;as is&quot; without warranties of any kind. We are not liable for any
              indirect, incidental, or consequential damages arising from your use of the Service.
              Our total liability is limited to the amount you paid for the Service in the preceding 12 months.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">9. Termination</h2>
            <p className="text-gray-600">
              Either party may terminate the agreement at any time. We reserve the right to suspend or
              terminate accounts that violate these terms. Upon termination, you may export your data
              within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">10. Governing Law</h2>
            <p className="text-gray-600">
              These terms are governed by the laws of Germany. The courts of Frankfurt am Main
              shall have exclusive jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mt-8 mb-4">11. Contact</h2>
            <p className="text-gray-600">
              For questions about these terms, please contact:<br />
              Email:{' '}
              <a href="mailto:info@book.gy" className="text-primary hover:underline">info@book.gy</a>
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
